services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    links:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: TX0TJUN5Z1BnhsBMS8g9
      DB_HOST: bia.cc5o0y2wqori.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      ## NAO PRECISA NO BOOTCAMP DAQUI PRA BAIXO ##
      # DB_SECRET_NAME: 
      # DB_REGION: 
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY:
      # DEBUG_SECRET: 
      # IS_LOCAL: true 
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/api/versao"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 5s     
  database:
    image: postgres:16.1
    container_name: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bia"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
